use std::sync::LazyLock;

use fancy_regex::{Captures as FancyCaptures, Regex as FancyRegex};
use phf::phf_map;

pub static MACROS: phf::Map<&str, char> = phf_map! {
    "Delta" => 'Δ',
    "Downarrow" => '⇓',
    "Gamma" => 'Γ',
    "Lambda" => 'Λ',
    "Leftarrow" => '⇐',
    "Leftrightarrow" => '⇔',
    "Omega" => 'Ω',
    "Phi" => 'Φ',
    "Pi" => 'Π',
    "Psi" => 'Ψ',
    "Rightarrow" => '⇒',
    "Sigma" => 'Σ',
    "Theta" => 'Θ',
    "Uparrow" => '⇑',
    "Upsilon" => 'Υ',
    "Vert" => '‖',
    "Xi" => 'Ξ',
    "alpha" => 'α',
    "approx" => '≈',
    "beta" => 'β',
    "bigcap" => '⋂',
    "bigcup" => '⋃',
    "cap" => '∩',
    "cdot" => '⋅',
    "cdots" => '⋯',
    "chi" => 'χ',
    "circ" => '∘',
    "coloneqq" => '≔',
    "complement" => '∁',
    "cong" => '≅',
    "cross" => '×',
    "cup" => '∪',
    "ddots" => '⋱',
    "delta" => 'δ',
    "div" => '÷',
    "downarrow" => '↓',
    "dots" => '…',
    "ell" => 'ℓ',
    "emptyset" => '∅',
    "epsilon" => 'ϵ',
    "equiv" => '≡',
    "eta" => 'η',
    "eqqcolon" => '≕',
    "exists" => '∃',
    "forall" => '∀',
    "gamma" => 'γ',
    "ge" => '≥',
    "geq" => '≥',
    "gg" => '≫',
    "ggg" => '⋙',
    "iint" => '∬',
    "iiint" => '∭',
    "in" => '∈',
    "infty" => '∞',
    "int" => '∫',
    "iota" => 'ι',
    "kappa" => 'κ',
    "lambda" => 'λ',
    "land" => '∧',
    "langle" => '⟨',
    "ldots" => '…',
    "le" => '≤',
    "leftarrow" => '←',
    "leftrightarrow" => '↔',
    "leq" => '≤',
    "lfloor" => '⌊',
    "ll" => '≪',
    "lll" => '⋘',
    "lnot" => '¬',
    "lor" => '∨',
    "mapsto" => '↦',
    "mp" => '∓',
    "mu" => 'μ',
    "nabla" => '∇',
    "ne" => '≠',
    "neg" => '¬',
    "neq" => '≠',
    "ni" => '∋',
    "notin" => '∉',
    "nu" => 'ν',
    "oint" => '∮',
    "omega" => 'ω',
    "oplus" => '⊕',
    "otimes" => '⊗',
    "partial" => '∂',
    "perp" => '⊥',
    "phi" => 'ϕ',
    "pi" => 'π',
    "pm" => '±',
    "prod" => '∏',
    "propto" => '∝',
    "psi" => 'ψ',
    "rangle" => '⟩',
    "rfloor" => '⌋',
    "rho" => 'ρ',
    "rightarrow" => '→',
    "setminus" => '∖',
    "sigma" => 'σ',
    "sim" => '∼',
    "simeq" => '≃',
    "subset" => '⊂',
    "subseteq" => '⊆',
    "sum" => '∑',
    "supset" => '⊃',
    "supseteq" => '⊇',
    "tau" => 'τ',
    "theta" => 'θ',
    "times" => '×',
    "to" => '→',
    "top" => '⊤',
    "uparrow" => '↑',
    "upsilon" => 'υ',
    "varepsilon" => 'ε',
    "varphi" => 'φ',
    "varpi" => 'ϖ',
    "varnothing" => '∅',
    "varsigma" => 'ς',
    "vartheta" => 'ϑ',
    "vdots" => '⋮',
    "xi" => 'ξ',
    "zeta" => 'ζ',
};

static MACRO_RE: LazyLock<FancyRegex> =
    LazyLock::new(|| FancyRegex::new(r"\\([a-zA-Z]+)(?![a-zA-Z])").unwrap());

pub fn replace(text: &str) -> String {
    MACRO_RE
        .replace_all(text, |caps: &FancyCaptures<str>| {
            let name = caps.get(1).unwrap().as_str();
            MACROS
                .get(name)
                .map_or_else(|| caps.get(0).unwrap().as_str().to_owned(), ToString::to_string)
        })
        .into_owned()
}
