use std::sync::LazyLock;

use fancy_regex::Regex as FancyRegex;
use phf::phf_map;
use regex::Regex;

pub static ENTITIES: phf::Map<&str, char> = phf_map! {
    "&Alpha;" => 'Α',
    "&Beta;" => 'Β',
    "&Chi;" => 'Χ',
    "&Delta;" => 'Δ',
    "&Epsilon;" => 'Ε',
    "&Eta;" => 'Η',
    "&Gamma;" => 'Γ',
    "&Iota;" => 'Ι',
    "&Kappa;" => 'Κ',
    "&Lambda;" => 'Λ',
    "&Mu;" => 'Μ',
    "&Nu;" => 'Ν',
    "&Omega;" => 'Ω',
    "&Omicron;" => 'Ο',
    "&Phi;" => 'Φ',
    "&Pi;" => 'Π',
    "&Psi;" => 'Ψ',
    "&Rho;" => 'Ρ',
    "&Sigma;" => 'Σ',
    "&Tau;" => 'Τ',
    "&Theta;" => 'Θ',
    "&Upsilon;" => 'Υ',
    "&Xi;" => 'Ξ',
    "&Zeta;" => 'Ζ',
    "&alpha;" => 'α',
    "&and;" => '∧',
    "&asymp;" => '≈',
    "&beta;" => 'β',
    "&bull;" => '•',
    "&cap;" => '∩',
    "&chi;" => 'χ',
    "&cup;" => '∪',
    "&darr;" => '↓',
    "&deg;" => '°',
    "&delta;" => 'δ',
    "&divide;" => '÷',
    "&empty;" => '∅',
    "&epsilon;" => 'ε',
    "&equiv;" => '≡',
    "&eta;" => 'η',
    "&exist;" => '∃',
    "&forall;" => '∀',
    "&gamma;" => 'γ',
    "&ge;" => '≥',
    "&gg;" => '≫',
    "&hArr;" => '⇔',
    "&harr;" => '↔',
    "&hellip;" => '…',
    "&in;" => '∈',
    "&infin;" => '∞',
    "&int;" => '∫',
    "&iota;" => 'ι',
    "&kappa;" => 'κ',
    "&lArr;" => '⇐',
    "&lambda;" => 'λ',
    "&larr;" => '←',
    "&le;" => '≤',
    "&ll;" => '≪',
    "&mdash;" => '—',
    "&minus;" => '−',
    "&mu;" => 'μ',
    "&nabla;" => '∇',
    "&nbsp;" => '\u{00A0}',
    "&ndash;" => '–',
    "&ne;" => '≠',
    "&not;" => '¬',
    "&notin;" => '∉',
    "&nu;" => 'ν',
    "&ocirc;" => 'ô',
    "&omega;" => 'ω',
    "&or;" => '∨',
    "&para;" => '¶',
    "&part;" => '∂',
    "&phi;" => 'φ',
    "&pi;" => 'π',
    "&plusmn;" => '±',
    "&prime;" => '′',
    "&prod;" => '∏',
    "&prop;" => '∝',
    "&psi;" => 'ψ',
    "&rArr;" => '⇒',
    "&radic;" => '√',
    "&rarr;" => '→',
    "&rho;" => 'ρ',
    "&sdot;" => '⋅',
    "&sect;" => '§',
    "&sigma;" => 'σ',
    "&sub;" => '⊂',
    "&sube;" => '⊆',
    "&sum;" => '∑',
    "&sup;" => '⊃',
    "&supe;" => '⊇',
    "&tau;" => 'τ',
    "&theta;" => 'θ',
    "&times;" => '×',
    "&upsilon;" => 'υ',
    "&xi;" => 'ξ',
    "&zeta;" => 'ζ',
};

static LT_RE: LazyLock<FancyRegex> =
    LazyLock::new(|| FancyRegex::new("&lt;(?![a-zA-Z0-9])").unwrap());

static ENTITY_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new("&[a-zA-Z]+;").unwrap());

pub fn replace(text: &str) -> String {
    let text = ENTITY_RE.replace_all(text, |caps: &regex::Captures| {
        let entity = caps.get(0).unwrap().as_str();
        ENTITIES.get(entity).map_or_else(|| entity.to_owned(), |&c| c.to_string())
    });
    let text = text.replace("&gt;", ">");
    LT_RE.replace_all(&text, "<").into_owned()
}
